
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"  # 主应用端口
      - "9001:9001"  # 天气服务端口
      - "9002:9002"  # 订单服务端口
    environment:
      - PYTHONUNBUFFERED=1

  nginx:
    image: nginx:latest
    ports:
      - "9000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ./app/static:/app/static
    depends_on: 
      - app